# Generated by Django 5.0 on 2024-02-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='adress',
            new_name='address',
        ),
    ]
