# Generated by Django 5.0 on 2024-02-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0002_rename_adress_vendor_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='acknowledgment_date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='items',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quality_rating',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='status',
        ),
    ]
