# Generated by Django 5.0 on 2024-02-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0003_remove_purchase_acknowledgment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='acknowledgment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='issue_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='items',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='order_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='quality_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
