# Generated by Django 5.0 on 2024-02-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0004_purchase_acknowledgment_date_purchase_delivery_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='delivery_date',
            new_name='expected_delivery_date',
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivered_date',
            field=models.DateTimeField(null=True),
        ),
    ]
